### ISSUE TITLE
OPU simulated device doc

### ISSUE THREAD

**Issue by lucgiffon** [lightonai/lightonml#1]
Hello,
I did not find any specific documentation for using an OPU simulated device and running my first tests on my computer. Sorry in advance if I've just missed it ;)

I've eventually found how to do it in the API reference:

`opu = OPU(n_components=d, opu_device=SimulatedOpuDevice())
`
but it costed more time than I would have liked. I think it would be a nice addition to add a short specific example on how to do it in the documentation? maybe a note about this in the "Get started with the OPU" section of the documentation? 

Bye

**Comment by CharlesB2** [comment]
Thanks for feedback, indeed current documentation is lacking details about this...

Since simulating an OPU takes a lot of resources, you need to limit the number of components and features with the following (change the dimensions according to the capacity/memory of your local machine):

```
sim_device = SimulatedOpuDevice()
opu = OPU(n_components=1000, max_n_features=1000, opu_device=sim_device)
```

Will make it clearer in the docs
